[workspace]
members = [".", "sea-connection", "sea-orm-macros", "sea-orm-codegen"]

[package]
name = "sea-orm"
version = "0.7.1"
authors = ["Chris Tsang <tyt2y7@gmail.com>"]
edition = "2021"
description = "🐚 An async & dynamic ORM for Rust"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/sea-orm"
repository = "https://github.com/SeaQL/sea-orm"
categories = ["database"]
keywords = ["async", "orm", "mysql", "postgres", "sqlite"]

[package.metadata.docs.rs]
features = ["default", "sqlx-all", "mock", "runtime-async-std-native-tls"]
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "sea_orm"
path = "src/lib.rs"

[dependencies]
async-stream = { version = "^0.3" }
async-trait = { version = "^0.1" }
chrono = { version = "^0", optional = true }
time = { version = "^0.2", optional = true }
futures = { version = "^0.3" }
futures-util = { version = "^0.3" }
tracing = { version = "0.1", features = ["log"] }
rust_decimal = { version = "^1", optional = true }
sea-orm-macros = { version = "^0.7.0", path = "sea-orm-macros", optional = true }
sea-connection = { version = "^0.7.1", path = "sea-connection" }
sea-query = { version = "^0.23.0", features = ["thread-safe"] }
sea-strum = { version = "^0.23", features = ["derive", "sea-orm"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1", optional = true }
uuid = { version = "0.8", features = ["serde", "v4"], optional = true }
ouroboros = "0.15"
url = "^2.2"
once_cell = "1.8"

[dev-dependencies]
smol = { version = "^1.2" }
smol-potat = { version = "^1.1" }
async-std = { version = "^1.9", features = ["attributes", "tokio1"] }
tokio = { version = "^1.6", features = ["full"] }
actix-rt = { version = "2.2.0" }
maplit = { version = "^1" }
rust_decimal_macros = { version = "^1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sea-orm = { path = ".", features = ["mock", "debug-print"] }
pretty_assertions = { version = "^0.7" }

[features]
debug-print = ["sea-connection/debug-print"]
default = [
    "macros",
    "with-json",
    "with-chrono",
    "with-rust_decimal",
    "with-uuid",
    "with-time",
]
macros = ["sea-orm-macros"]
mock = ["sea-connection/mock"]
with-json = ["serde_json", "sea-connection/with-json"]
with-chrono = ["chrono", "sea-connection/with-chrono"]
with-rust_decimal = ["rust_decimal", "sea-connection/with-rust_decimal"]
with-uuid = ["uuid", "sea-connection/with-uuid"]
with-time = ["time", "sea-connection/with-time"]
sqlx-all = ["sea-connection/sqlx-all"]
sqlx-dep = ["sea-connection/sqlx-dep"]
sqlx-json = ["sea-connection/sqlx-json"]
sqlx-chrono = ["sea-connection/sqlx-chrono"]
sqlx-decimal = ["sea-connection/sqlx-decimal"]
sqlx-uuid = ["sea-connection/sqlx-uuid"]
sqlx-time = ["sea-connection/sqlx-time"]
sqlx-mysql = ["sea-connection/sqlx-mysql"]
sqlx-postgres = ["sea-connection/sqlx-postgres"]
sqlx-sqlite = ["sea-connection/sqlx-sqlite"]
runtime-async-std =["sea-connection/runtime-async-std"]
runtime-async-std-native-tls = ["sea-connection/runtime-async-std-native-tls"]
runtime-async-std-rustls = ["sea-connection/runtime-async-std-rustls"]
runtime-actix =["sea-connection/runtime-actix"]
runtime-actix-native-tls = ["sea-connection/runtime-actix-native-tls"]
runtime-actix-rustls = ["sea-connection/runtime-actix-rustls"]
runtime-tokio =["sea-connection/runtime-tokio"]
runtime-tokio-native-tls = ["sea-connection/runtime-tokio-native-tls"]
runtime-tokio-rustls = ["sea-connection/runtime-tokio-rustls"]
