[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-schema = { git = "https://github.com/SeaQL/sea-schema.git", branch = "sea-orm/conn-relax-sized-bound", version = "^0.5.0", default-features = false, features = [ "migration", "debug-print" ] }
entity = { path = "../entity" }
rocket = { version = "0.5.0-rc.1" }
